stages:
- name: test
  steps:
  - runScriptConfig:
      image: java:8
      shellScript: mvn test
- name: package
  steps:
  - runScriptConfig:
      image: java:8
      shellScript: mvn clean package
- name: docker
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: beyondcoding/theunbelievableproject
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
